# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
paginate_path: "/blogs"
paginate: 3 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude
